### PR TITLE
Use alpine for smaller image, update go version to 1.13.4

### PR DESCRIPTION
**Pull request by miketonks**
Make image smaller, using alpine base
Update to latest go version

Borrowing heavily from https://github.com/docker-library/golang/blob/f30f0428221b94c7dcb414ebdcea83106df20897/1.13/alpine3.10/Dockerfile

### CODE REVIEW

**Comment by miketonks** [comment]
Looks like I did something wrong, as Travis fails.  Looks like it's running the old code, not my updated version.  Or perhaps failed to build locally.

Meanwhile I've created two new repos for new languages:

* https://github.com/hf-dojo/go-convey

* https://github.com/hf-dojo/go-testify

using golang base with two different test frameworks.  Not sure how to do a PR for those as it needs new languages repos to be created on github first?

**Comment by JonJagger** [comment]
Fantastic. I will probably get to this tomorrow. Big thanks :-)

**Comment by JonJagger** [comment]
Hi Mike,
I've updated the existing go repos and added new repos for convey and testify
https://github.com/cyber-dojo-languages/go-testify
https://github.com/cyber-dojo-languages/go-convey

I had to add
RUN apk add build-base
to the Dockerfile for testify otherwise it complained about needing gcc.
I also needed to increase max_seconds in its manifest.json file as it seems quite slow.

All now live :-) 
Huge thanks for this.
Cheers
Jon
P.S. Are you by any chance the Michael I met in Cisco,Lysaker last week?

**Comment by JonJagger** [comment]
Now live :-)

**Comment by miketonks** [comment]
Hi Jon,

Amazing, thanks for the quick turn around.  We met at Bedruthan,  a few weeks ago.

**Comment by JonJagger** [comment]
Ah! Thanks again :-)

**Pull request closed without merging**
